version: '3.4'
services:
  diego:
    build:
      context: .
      target: diego
      dockerfile: ./Dockerfile
    container_name: diego
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - .:/diego
    tty: true