version: '3.4'
services:
  proxy:
    restart: always
    container_name: diego-dev-nginx
    build:
      dockerfile: Dockerfile
      target: diego-dev-nginx
      context: ./nginx
    ports:
      - "80:80"
    links:
      - diego-dev
  
  diego-dev-redis:
    restart: always
    image: redis
    container_name: diego-dev-redis
    expose:
      - 6379

  diego-dev-mongo:
    image: mongo
    restart: always
    container_name: diego-dev-mongo
    volumes:
    - ./data/db:/var/micro-data/mongodb/data/db
    ports:
    - "27017:27017"
    expose:
      - 27017

  diego-dev:
    build:
      context: .
      target: diego-dev
      dockerfile: ./Dockerfile
    container_name: diego-dev
    restart: always
    ports:
      - "8080:8080"
    links:
      - diego-dev-redis
      - diego-dev-mongo
    volumes:
      - .:/diego
    tty: true
    environment:
      PORT: 8080
      REDIS_URL: redis://diego-dev-redis
      MONGO_URL: mongodb://diego-dev-mongo
     