version: '3.4'
services:
  proxy:
    container_name: diego-prod-nginx
    build:
      dockerfile: Dockerfile
      target: diego
      context: ./nginx
    ports:
      - "80:80"
    links:
      - diego
    
  diego:
    build:
      context: .
      target: diego
      dockerfile: ./Dockerfile
    container_name: diego
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - .:/diego
    tty: true
    environment:
      PORT: 8081