version: '3.4'

  # docker-compose     -f docker-compose.yml     -f docker-compose.dev.yml up
  # docker-compose     -f docker-compose.yml     -f docker-compose.dev.yml up -d
  # docker-compose     -f docker-compose.yml     -f docker-compose.dev.yml --build
  # docker-compose     -f docker-compose.yml     -f docker-compose.dev.yml up --build -d