version: '3.4'
services:
  proxy:
    container_name: diego-prod-nginx
    build:
      dockerfile: Dockerfile
      target: diego-nginx
      context: ./nginx
    ports:
      - "80:80"
    links:
      - diego

  diego-redis:
    image: redis
    container_name: diego-redis
    expose:
      - 6380
    
  diego:
    build:
      context: .
      target: diego
      dockerfile: ./Dockerfile
    container_name: diego
    restart: always
    ports:
      - "8081:8081"
    links:
      - diego-redis
    volumes:
      - .:/diego
    tty: true
    environment:
      PORT: 8081
      REDIS_URL: redis://diego-redis