version: '3.4'
services:
  proxy:
    restart: always
    container_name: diego-prod-nginx
    build:
      dockerfile: Dockerfile
      target: diego-nginx
      context: ./nginx
    ports:
      - "80:80"
    links:
      - diego

  diego-redis:
    restart: always
    image: redis
    container_name: diego-redis
    expose:
      - 6380
  
  diego-db:
    image: aashreys/mongo-auth:latest
    container_name: diego-db
    restart: always
    ports:
    - "27018:27018"
    command: mongod --port 27018
    expose:
      - 27018
    environment:
      AUTH: "yes"
      MONGODB_ADMIN_USER: root
      MONGODB_ADMIN_PASS: root
      MONGODB_APPLICATION_DATABASE: diego
      MONGODB_APPLICATION_USER: admin
      MONGODB_APPLICATION_PASS: admin
    
  diego:
    build:
      context: .
      target: diego
      dockerfile: ./Dockerfile
    container_name: diego
    restart: always
    ports:
      - "8081:8081"
    links:
      - diego-redis
      - diego-db
    volumes:
      - .:/diego
    tty: true
    environment:
      PORT: 8081
      REDIS_URL: redis://diego-redis
      MONGO_URL: mongodb://diego-db:27018/diego
